
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-2
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-2
pull_requests: [{"author":{"id":"U_kgDOBsO-4g","is_bot":false,"login":"richardfang888","name":"Richard Fang"},"headRefName":"richard-tests","number":105,"title":"Richard- MenuItemReview Testing","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-2/pull/105"},{"author":{"id":"MDQ6VXNlcjUzNzQwNDY0","is_bot":false,"login":"ukyl","name":""},"headRefName":"ukyl-tests","number":104,"title":"RecommendationRequest Integration and End to End testing","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-2/pull/104"},{"author":{"id":"U_kgDOBdC-cw","is_bot":false,"login":"nicoshinozaki","name":""},"headRefName":"Nico-h05","number":103,"title":"Nico h05","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-2/pull/103"},{"author":{"id":"U_kgDOBdHiDg","is_bot":false,"login":"NevMan1","name":""},"headRefName":"nevin-UCSBOrganization-test","number":102,"title":"hw 5 done","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-2/pull/102"},{"author":{"id":"U_kgDOBtOfzg","is_bot":false,"login":"abhishekambastha04","name":"Abhi"},"headRefName":"Abhishek-homework5","number":101,"title":"UCSBDiningCommonsMenu Item - added E2E and integration testing","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-2/pull/101"}]
