
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-2
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjUzNzQwNDY0","is_bot":false,"login":"ukyl","name":""},"headRefName":"ukyl-RecommendationRequest-frontend-allPages","number":91,"title":"Ukyl -  RecommendationRequest EditPage","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-2/pull/91"},{"author":{"id":"MDQ6VXNlcjUzNzQwNDY0","is_bot":false,"login":"ukyl","name":""},"headRefName":"ukyl-RecommendationRequest-frontend-indexPage","number":90,"title":"Ukyl - RecommendationRequestIndexPage Implementation","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-2/pull/90"},{"author":{"id":"MDQ6VXNlcjUzNzQwNDY0","is_bot":false,"login":"ukyl","name":""},"headRefName":"ukyl-RecommendationRequest-frontend-createPage","number":88,"title":"Ukyl - RecommendationRequestCreatePage Implementation","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-2/pull/88"},{"author":{"id":"MDQ6VXNlcjUzNzQwNDY0","is_bot":false,"login":"ukyl","name":""},"headRefName":"ukyl-RecommendationRequest-frontend-placeholders","number":87,"title":"Ukyl - RecommendationRequest PlaceHolder","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-2/pull/87"},{"author":{"id":"U_kgDOBdHiDg","is_bot":false,"login":"NevMan1","name":""},"headRefName":"nevin-UCSBOrganization-Index","number":85,"title":"Nevin ucsb organization index","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-2/pull/85"}]
