
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-2
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-2
pull_requests: [{"author":{"id":"U_kgDOBdC-cw","is_bot":false,"login":"nicoshinozaki","name":""},"headRefName":"Nico-Articles-Fixtures","number":69,"title":"Articles - Create fixtures for Articles","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-2/pull/69"},{"author":{"id":"U_kgDOBtOfzg","is_bot":false,"login":"abhishekambastha04","name":"Abhi"},"headRefName":"Abhishek-CRUDFileCopyOver","number":68,"title":"completed the file copy over for dining commons menu items","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-2/pull/68"},{"author":{"id":"U_kgDOBdC-cw","is_bot":false,"login":"nicoshinozaki","name":""},"headRefName":"Nico-Articles-Backend","number":66,"title":"Articles - Copy files for Backend CRUD API Articles from team02","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-2/pull/66"},{"author":{"id":"U_kgDOBdHiDg","is_bot":false,"login":"NevMan1","name":""},"headRefName":"nevin-UCSBOrganization-fixture","number":65,"title":"Nevin ucsb organization fixture","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-2/pull/65"},{"author":{"id":"U_kgDOBdHiDg","is_bot":false,"login":"NevMan1","name":""},"headRefName":"nevin-UCSBOrganization-backend","number":64,"title":"Crud","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-2/pull/64"},{"author":{"id":"MDQ6VXNlcjUzNzQwNDY0","is_bot":false,"login":"ukyl","name":""},"headRefName":"ukyl-readme","number":63,"title":"Ukyl - updated readme links and table","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-2/pull/63"},{"author":{"id":"MDQ6VXNlcjUzNzQwNDY0","is_bot":false,"login":"ukyl","name":""},"headRefName":"ukyl-RecommendationRequest-frontend-fixtures","number":62,"title":"Ukyl - Added recommendationRequest frontend fixtures","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-2/pull/62"},{"author":{"id":"MDQ6VXNlcjUzNzQwNDY0","is_bot":false,"login":"ukyl","name":""},"headRefName":"ukyl-RecommendationRequest-backend","number":61,"title":"Ukyl - Recommendation Request Backend CRUD API copyover","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-2/pull/61"}]
